# Change these first
owner: SEAMEO-SEN # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main Site
    url: https://seameosen.edu.my
  - name: International Conference on Special Education Site
    url: https://icse.seameosen.edu.my
  - name: Innovation for Disability-Inclusive Education Competition
    url: https://idiec.seameosen.edu.my
  - name: SEAMEO SEN Library
    url: https://library.seameosen.edu.my
  - name: SEAMEO SEN Publication
    url: https://publication.seameosen.edu.my
  - name: SEAMEO SEN Integrated Excellence System
    url: https://sies.seameosen.edu.my
  - name: SEAMEO SEN Onestop Management System
    url: https://onestop.seameosen.edu.my

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.seameosen.edu.my
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/SEAMEO-SEN/publications/develop/static/img/badge_logo_seameosen.png
  name: SEAMEO SEN
  introTitle: "SEAMEO SEN Monitoring System"
  introMessage: monitor SEAMEO SEN web apps
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
